define(function(){
 	"use strict";
 	return {
 		futureStates:[
 			{
 				"module":"app.states.userInfo",
 				"stateName":"states.userInfo",
 				"url":"/userInfo","type":"ocLazyLoad"
 			},
 			/*{
 				"module":"app.states.courseDetail",
 				"stateName":"states.courseDetail",
 				"url":"/courseDetail","type":"ocLazyLoad"
 			},
 			{
 				"module":"app.states.exam",
 				"stateName":"states.exam",
 				"url":"/exam","type":"ocLazyLoad"
 			},
 			{
 				"module":"app.states.feedback",
 				"stateName":"states.feedback",
 				"url":"/feedback",
 				"type":"ocLazyLoad"
 			},
 			{
 				"module":"app.states.mySelectCourse",
 				"stateName":"states.mySelectCourse",
 				"url":"/mySelectCourse",
 				"type":"ocLazyLoad"
 			},
 			{
 				"module":"app.states.personCenter",
 				"stateName":"states.personCenter",
 				"url":"/personCenter",
 				"type":"ocLazyLoad"
 			},
 			{
 				"module":"app.states.personInfo",
 				"stateName":"states.personInfo",
 				"url":"/personInfo",
 				"type":"ocLazyLoad"
 			},
 			{
 				"module":
 				"app.states.play",
 				"stateName":"states.play",
 				"url":"/play",
 				"type":"ocLazyLoad"
 			},
 			{
 				"module":"app.states.questionView",
 				"stateName":"states.questionView",
 				"url":"/questionView",
 				"type":"ocLazyLoad"
 			}*/
 		]
 	}
});