define(function(){
	"use strict";
	return {
		modules:[
			{
				"reconfig":true,
				"name":"app.states.userInfo",
				"files":["states/userInfo-states"]
			},
			{
				"reconfig":true,
				"name":"app.states.adver",
				"files":["states/adver-states"]
			},
			{
				"reconfig":true,
				"name":"app.states.advice",
				"files":["states/advice-states"]
			},
			/*{
				"reconfig":true,
				"name":"app.states.courseDetail",
				"files":["states/courseDetail-state"]
			},
			{
				"reconfig":true,
				"name":"app.states.exam",
				"files":["states/exam-state"]
			},
			{
				"reconfig":true,
				"name":"app.states.feedback",
				"files":["states/feedback-state"]
			},
			{
				"reconfig":true,
				"name":"app.states.mySelectCourse",
				"files":["states/mySelectCourse-state"]
			},
			{
				"reconfig":true,
				"name":"app.states.personCenter",
				"files":["states/personCenter-state"]
			},
			{
				"reconfig":true,
				"name":"app.states.personInfo",
				"files":["states/personInfo-state"]
			},
			{
				"reconfig":true,
				"name":"app.states.play",
				"files":["states/play-state"]
			},
			{
				"reconfig":true,
				"name":"app.states.questionView",
				"files":["states/questionView-state"]
			}*/
		]
	}
});