var app = angular.module('app', ['ui.router'])

/*app.config(function($stateProvider,$urlRouterProvider){
	$urlRouterProvider.otherwise('/head');

	$stateProvider.state('head',{
		url:'/head',
		templateUrl:'tpls/head.html'
	})
	.state('part1',{
		url:'/part1',
		templateUrl:'tpls/part1.html'
	})
	.state('part2',{
		url:'/part2',
		templateUrl:'tpls/part2.html'
	})
	.state('part3',{
		url:'/part3',
		templateUrl:'tpls/part3.html'
	})
	.state('part3.part4',{
		url:'/part4',
		templateUrl:'tpls/part4.html'
	})
})*/

app.config(function($stateProvider,$urlRouterProvider) {
	$urlRouterProvider.otherwise('/part1');

	$stateProvider
	.state('state',{
		url:'/',
		views:{
			"@":{
				templateUrl:'tpls/content.html'
			},
			"header@state":{
				templateUrl:'tpls/head.html'
			}
		}
	})
	.state('state.part1',{
		url:'part1',
		views:{
			"body@state":{
				templateUrl:'tpls/part1.html'
			}
		}
	})
	.state('state.part2',{
		url:'part2',
		views:{
			"body@state":{
				templateUrl:'tpls/part2.html'
			}
		}
	})
	.state('state.part3',{
		url:'part3',
		views:{
			"body@state":{
				templateUrl:'tpls/part3.html'
			},
			'part4@state.part3':{
				templateUrl:'tpls/part4.html'
			}
		}
	})
	/*.state('state.part3.part4',{
		url:'/part4',
		views:{
			"":{
				templateUrl:'tpls/part4.html'
			}
		}
	})*/
})